name = "cyberteckmaster"
type = "javascript"
compatibility_date = "2024-05-01"
account_id = "your-cloudflare-account-id"
workers_dev = false

routes = [
  { pattern = "cyberteckmaster.com/*", zone_id = "your-zone-id" }
]

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
zone_id = "your-zone-id"
account_id = "your-cloudflare-account-id"
route = "cyberteckmaster.com/*"